# https://docs.frigate.video/configuration/reference/

version: 0.17-0

mqtt:
  host: mosquitto

tls:
  enabled: false

go2rtc:
  streams:
    tapo_c200:
      - onvif://{FRIGATE_TAPO_C200_USER}:{FRIGATE_TAPO_C200_PASSWORD}@tapo-c200:2020
      - tapo://{FRIGATE_TAPO_C200_CLOUD_PASSWORD}@tapo-c200 # Vidéo + 2-way (HTTPS)
    tapo_c200_sub: onvif://{FRIGATE_TAPO_C200_USER}:{FRIGATE_TAPO_C200_PASSWORD}@tapo-c200:2020?subtype=1
  webrtc:
    candidates:
      - ${WEBRTC_LOCAL_CANDIDATE} # Local access

birdseye:
  enabled: false

cameras:
  tapo_c200:
    enabled: true # Enables camera at restart, even if it was disabled within the UI
    live:
      streams:
        Default: tapo_c200
    ffmpeg:
      hwaccel_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/tapo_c200_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/tapo_c200
          roles:
            - record
            - audio
    objects:
      filters:
        person:
          min_score: 0.3
          threshold: 0.5

    onvif: # Only for PTZ
      host: tapo-c200
      port: 2020
      user: "{FRIGATE_TAPO_C200_USER}"
      password: "{FRIGATE_TAPO_C200_PASSWORD}"

audio:
  enabled: true

detect:
  enabled: true

record:
  enabled: true
  continuous:
    days: 0
  motion:
    days: 10

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true

detectors:
  cpu1:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

face_recognition:
  enabled: true
  model_size: small
semantic_search:
  enabled: true
  model_size: small
