api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
  # websecure:
  #   address: ":443"

providers:
  docker:
    exposedByDefault: false
    defaultRule: 'Host(`{{ index .Labels "com.docker.compose.service" }}.nicolas-delahaie.fr`)' # STATIC !
  file:
    filename: /etc/traefik/dynamic_conf.yml
    watch: true

accessLog:
  filters:
    statusCodes: ["400-599"]

# certificatesResolvers:
#   letsencrypt:
#     acme:
#       email: you@example.com
#       storage: /etc/traefik/acme.json
#       httpChallenge:
#         entryPoint: web