filenames:
  - /logs/traefik/*.log
labels:
  type: traefik
---
source: journalctl
journalctl_filter:
  - "_SYSTEMD_UNIT=ssh.service"
labels:
  type: syslog
---
filenames:
  - /logs/authelia.log
labels:
  type: authelia
